import { motion, useScroll, useTransform, useMotionValue, useSpring } from "framer-motion";
import { useRef, useState } from "react";
import { ArrowRight, Zap, Target, TrendingUp, Flame, Apple, Calculator, UtensilsCrossed, Award, Users, BarChart3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import nutritionRobot from "@/assets/nutrition-robot.png";
const features = [
  {
    icon: Apple,
    title: "Food Database",
    description: "Access real-time nutrition data for thousands of foods worldwide.",
    color: "from-red-500/20 to-red-500/5",
    href: "/food-search",
  },
  {
    icon: Calculator,
    title: "Smart Calculator",
    description: "Calculate your BMR, TDEE, and personalized calorie targets.",
    color: "from-blue-500/20 to-blue-500/5",
    href: "/calculator",
  },
  {
    icon: UtensilsCrossed,
    title: "AI Diet Planner",
    description: "Get personalized meal plans generated by AI based on your goals.",
    color: "from-emerald-500/20 to-emerald-500/5",
    href: "/diet-planner",
  },
];

const stats = [
  { icon: Users, value: "10K+", label: "Active Users" },
  { icon: BarChart3, value: "500K+", label: "Foods Tracked" },
  { icon: Award, value: "98%", label: "Success Rate" },
];

// Interactive Robot Mascot with parallax effect
function RobotMascot() {
  const ref = useRef<HTMLDivElement>(null);
  const [isHovered, setIsHovered] = useState(false);
  
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  
  const springConfig = { stiffness: 150, damping: 20 };
  const rotateX = useSpring(useMotionValue(0), springConfig);
  const rotateY = useSpring(useMotionValue(0), springConfig);
  const scale = useSpring(1, springConfig);

  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!ref.current) return;
    
    const rect = ref.current.getBoundingClientRect();
    const centerX = rect.left + rect.width / 2;
    const centerY = rect.top + rect.height / 2;
    
    const mouseX = e.clientX - centerX;
    const mouseY = e.clientY - centerY;
    
    rotateX.set(mouseY * 0.02);
    rotateY.set(-mouseX * 0.02);
    x.set(mouseX * 0.05);
    y.set(mouseY * 0.05);
  };

  const handleMouseEnter = () => {
    setIsHovered(true);
    scale.set(1.05);
  };

  const handleMouseLeave = () => {
    setIsHovered(false);
    rotateX.set(0);
    rotateY.set(0);
    x.set(0);
    y.set(0);
    scale.set(1);
  };

  return (
    <motion.div
      ref={ref}
      onMouseMove={handleMouseMove}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      style={{
        rotateX,
        rotateY,
        x,
        y,
        scale,
        perspective: 1000,
      }}
      className="relative cursor-pointer"
    >
      {/* Glow effect */}
      <motion.div
        animate={{
          opacity: isHovered ? 0.8 : 0.4,
          scale: isHovered ? 1.1 : 1,
        }}
        className="absolute inset-0 bg-gradient-to-b from-primary/30 via-primary/10 to-transparent rounded-full blur-3xl -z-10"
      />
      
      {/* Floating animation */}
      <motion.div
        animate={{
          y: [0, -10, 0],
        }}
        transition={{
          duration: 4,
          repeat: Infinity,
          ease: "easeInOut",
        }}
      >
        <img
          src={nutritionRobot}
          alt="NutriTrack AI Assistant"
          className="w-full max-w-md h-auto drop-shadow-2xl"
        />
      </motion.div>

      {/* Sparkle effects */}
      {isHovered && (
        <>
          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            animate={{ opacity: 1, scale: 1 }}
            className="absolute top-10 right-10 w-3 h-3 bg-primary rounded-full animate-pulse"
          />
          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.1 }}
            className="absolute bottom-20 left-5 w-2 h-2 bg-accent rounded-full animate-pulse"
          />
        </>
      )}
    </motion.div>
  );
}

function HeroSection() {
  const navigate = useNavigate();
  
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden pt-20 pb-32">
      {/* Background gradients */}
      <div className="absolute inset-0">
        <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-gradient-to-bl from-primary/15 to-transparent rounded-full blur-3xl -translate-y-1/2 translate-x-1/3" />
        <div className="absolute bottom-0 left-0 w-[600px] h-[600px] bg-gradient-to-tr from-accent/10 to-transparent rounded-full blur-3xl translate-y-1/3 -translate-x-1/4" />
      </div>

      <div className="container relative">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left content */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
          >
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 text-primary text-sm font-medium mb-6"
            >
              <Flame className="w-4 h-4" />
              <span>Start your fitness journey today</span>
              <ArrowRight className="w-4 h-4" />
            </motion.div>

            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold text-foreground leading-[1.1] tracking-tight mb-6">
              Transform Your
              <br />
              <span className="relative">
                <span className="bg-gradient-to-r from-primary via-primary to-accent bg-clip-text text-transparent">
                  Nutrition
                </span>
                <motion.div
                  initial={{ scaleX: 0 }}
                  animate={{ scaleX: 1 }}
                  transition={{ duration: 0.8, delay: 0.3 }}
                  className="absolute -bottom-2 left-0 right-0 h-3 bg-primary/20 rounded-full origin-left"
                />
              </span>
            </h1>

            <p className="text-lg md:text-xl text-muted-foreground max-w-lg mb-8">
              Track calories, discover foods, and build sustainable habits with 
              the simplest nutrition platform designed for results.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 mb-12">
              <Button 
                variant="hero" 
                size="xl" 
                className="group text-lg px-8"
                onClick={() => navigate('/auth')}
              >
                Get Started Free
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Button>
              <Button 
                variant="outline" 
                size="xl" 
                className="text-lg px-8"
                onClick={() => navigate('/calculator')}
              >
                Calculate Calories
              </Button>
            </div>

            {/* Stats */}
            <div className="flex flex-wrap gap-8">
              {stats.map((stat, index) => (
                <motion.div
                  key={stat.label}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.4 + index * 0.1 }}
                  className="flex items-center gap-3"
                >
                  <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                    <stat.icon className="w-5 h-5 text-primary" />
                  </div>
                  <div>
                    <p className="text-2xl font-bold text-foreground">{stat.value}</p>
                    <p className="text-xs text-muted-foreground">{stat.label}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Right content - Robot Mascot */}
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="hidden lg:flex items-center justify-center relative"
          >
            <RobotMascot />
          </motion.div>
        </div>
      </div>
    </section>
  );
}

function FeaturesSection() {
  const navigate = useNavigate();
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "end start"],
  });

  const y = useTransform(scrollYProgress, [0, 1], [100, -100]);

  return (
    <section ref={ref} className="py-24 md:py-32 relative overflow-hidden bg-muted/30">
      <motion.div style={{ y }} className="absolute top-20 right-10 w-64 h-64 bg-primary/5 rounded-full blur-3xl" />
      
      <div className="container">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-accent/10 text-accent text-sm font-medium mb-4">
            <Zap className="w-4 h-4" />
            <span>Powerful Features</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
            Everything You Need
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
            Three powerful tools working together to transform your nutrition journey.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 40 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.15 }}
              whileHover={{ y: -8, scale: 1.02 }}
              onClick={() => navigate(feature.href)}
              className="group cursor-pointer"
            >
              <div className={`relative h-full bg-gradient-to-br ${feature.color} rounded-3xl p-8 border border-border/50 hover:border-primary/30 transition-all duration-300 overflow-hidden`}>
                {/* Hover glow */}
                <div className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                  <div className="absolute inset-0 bg-gradient-to-br from-primary/10 to-transparent" />
                </div>

                <div className="relative z-10">
                  <div className="w-16 h-16 rounded-2xl bg-card flex items-center justify-center mb-6 shadow-lg group-hover:shadow-xl transition-shadow">
                    <feature.icon className="w-8 h-8 text-primary" />
                  </div>
                  
                  <h3 className="text-2xl font-bold text-foreground mb-3">
                    {feature.title}
                  </h3>
                  <p className="text-muted-foreground mb-6">
                    {feature.description}
                  </p>
                  
                  <div className="flex items-center gap-2 text-primary font-medium group-hover:gap-3 transition-all">
                    <span>Explore</span>
                    <ArrowRight className="w-4 h-4" />
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FitnessShowcase() {
  return (
    <section className="py-24 md:py-32">
      <div className="container">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-4">
            Your Complete Wellness Hub
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
            From tracking to planning, we've got every aspect of your health journey covered.
          </p>
        </motion.div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">
          {[
            { emoji: "🏋️", label: "Strength Training", desc: "Build muscle mass" },
            { emoji: "🥗", label: "Healthy Eating", desc: "Balanced nutrition" },
            { emoji: "🏃", label: "Cardio Fitness", desc: "Burn calories" },
            { emoji: "🧘", label: "Mind & Body", desc: "Mental wellness" },
          ].map((item, index) => (
            <motion.div
              key={item.label}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              whileHover={{ scale: 1.05, y: -5 }}
              className="aspect-square rounded-3xl bg-gradient-to-br from-card to-muted border border-border/50 flex flex-col items-center justify-center cursor-pointer hover:shadow-lg hover:border-primary/30 transition-all duration-300"
            >
              <motion.span 
                className="text-5xl md:text-6xl mb-3"
                whileHover={{ scale: 1.2, rotate: [0, -10, 10, 0] }}
                transition={{ duration: 0.3 }}
              >
                {item.emoji}
              </motion.span>
              <span className="text-sm font-semibold text-foreground">{item.label}</span>
              <span className="text-xs text-muted-foreground mt-1">{item.desc}</span>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CTASection() {
  const navigate = useNavigate();
  
  return (
    <section className="py-24 md:py-32 bg-gradient-to-b from-muted/50 to-background">
      <div className="container">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="max-w-3xl mx-auto text-center"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
            <Target className="w-4 h-4" />
            <span>Ready to start?</span>
          </div>
          
          <h2 className="text-4xl md:text-5xl font-bold text-foreground mb-6">
            Take Control of Your
            <br />
            <span className="text-primary">Nutrition Today</span>
          </h2>
          
          <p className="text-lg text-muted-foreground mb-10 max-w-xl mx-auto">
            Join thousands of users who have transformed their health with our simple, 
            effective nutrition tracking platform.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button variant="hero" size="xl" className="gap-2 text-lg" onClick={() => navigate('/auth')}>
              Create Free Account
              <ArrowRight className="w-5 h-5" />
            </Button>
            <Button variant="outline" size="xl" className="text-lg" onClick={() => navigate('/food-search')}>
              Explore Foods
            </Button>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

export function HeroSections() {
  return (
    <>
      <HeroSection />
      <FeaturesSection />
      <FitnessShowcase />
      <CTASection />
    </>
  );
}
